import type { Metadata } from "next";
import { CookieSettingsButton } from "@/components/consent/cookie-settings-button";
import { LegalMeta, LegalPage } from "@/components/legal/legal-page";

export const metadata: Metadata = { title: "Cookie Policy", description: "How Clarify uses cookies and how you can control optional technologies." };

export default function CookiesPage() {
  return <LegalPage title="Cookie Policy" description="This policy explains the cookies and similar technologies Clarify uses and the choices available to you."><LegalMeta /><CookieSettingsButton className="mb-8" />
    <h2>1. What cookies are</h2><p>Cookies are small text files stored by a website in your browser. We may also use local storage, pixels, tags, and similar technologies. Some are necessary for a site to work; others support analytics or advertising.</p>
    <h2>2. Essential technologies</h2><p><strong>Purpose:</strong> authentication, session management, security, fraud prevention, network routing, consent storage, and core performance. These cannot be disabled through our preference tool because the Service may not function without them. Examples may include Clerk session cookies, authentication tokens, Cloudflare security cookies, and the <code>clarify_cookie_consent</code> local-storage record. These technologies generally do not require consent, although notice requirements may apply.</p>
    <h2>3. Analytics technologies</h2><p><strong>Purpose:</strong> understand feature usage, diagnose performance, analyze user journeys, and improve the Service. Providers may include Google Analytics and Microsoft Clarity. These are off until you opt in where consent is required, and Clarify applies this opt-in default globally. If enabled, providers may receive device, browser, usage, and approximate location information.</p>
    <h2>4. Advertising technologies</h2><p><strong>Purpose:</strong> ad delivery, personalization, frequency control, retargeting, conversion measurement, and attribution. Providers may include Google AdSense, Google Ads, Meta/Facebook Pixel, and future advertising partners. These are off until you explicitly opt in. Advertising partners may use information across sites as described in their policies.</p>
    <h2>5. Current technology table</h2><div className="overflow-x-auto"><table><thead><tr><th>Technology</th><th>Category</th><th>Typical duration</th><th>Status</th></tr></thead><tbody><tr><td>Clarify consent record</td><td>Essential</td><td>Until cleared or version changes</td><td>Active</td></tr><tr><td>Clerk authentication</td><td>Essential</td><td>Session or provider-defined</td><td>When authentication is enabled</td></tr><tr><td>Cloudflare security</td><td>Essential</td><td>Session or provider-defined</td><td>When deployed</td></tr><tr><td>Google Analytics</td><td>Analytics</td><td>Provider-defined</td><td>Only after opt-in and configuration</td></tr><tr><td>Microsoft Clarity</td><td>Analytics</td><td>Provider-defined</td><td>Only after opt-in and configuration</td></tr><tr><td>Google AdSense / advertising partners</td><td>Advertising</td><td>Provider-defined</td><td>Only after opt-in and configuration</td></tr></tbody></table></div>
    <h2>6. Your choices</h2><p>Use Cookie Settings to accept all, reject optional technologies, or choose categories independently. Essential technologies are always active. Withdrawing consent prevents future optional loading but does not automatically delete cookies already placed by a provider; you can clear them through browser settings. Disabling cookies in your browser may affect functionality.</p><p>Where supported, Clarify treats a Global Privacy Control signal as a direction to disable advertising and does not override that signal through the preference interface.</p>
    <h2>7. Changes and contact</h2><p>We may update this policy as our technologies change. Review the date above for the latest revision. Questions may be sent to <a href="mailto:privacy@useclarifyhome.us">privacy@useclarifyhome.us</a>.</p>
  </LegalPage>;
}
