import type { Metadata } from "next";
import { LegalMeta, LegalPage } from "@/components/legal/legal-page";

export const metadata: Metadata = { title: "Terms & Conditions", description: "Terms governing access to and use of Clarify." };

export default function TermsPage() {
  return <LegalPage title="Terms & Conditions" description="These terms govern your access to and use of Clarify and its homeowner education tools."><LegalMeta />
    <h2>1. Acceptance and eligibility</h2><p>By accessing or using Clarify, you agree to these Terms. If you do not agree, do not use the Service. You must be at least 18, or the age of legal majority where you live, and able to form a binding contract.</p>
    <h2>2. Service description</h2><p>Clarify provides educational calculators, estimates, comparisons, content, and homeowner decision-support tools. Features may change, be unavailable, contain errors, or differ by location. Clarify is not a lender, mortgage broker, insurer, real estate adviser, tax adviser, law firm, or fiduciary. Results are estimates and are not financial, legal, tax, insurance, or investment advice, an appraisal, a loan approval, or an offer of credit.</p>
    <h2>3. Accounts</h2><p>You must provide accurate information, keep credentials confidential, promptly update account details, and notify us of suspected unauthorized access. You are responsible for activity under your account. We may require verification or refuse registration where permitted by law.</p>
    <h2>4. Acceptable use</h2><p>You may use the Service only lawfully and for its intended purposes. You may not interfere with security or operation; scrape or access the Service through unauthorized automation; reverse engineer except where law prohibits restriction; upload malware; impersonate others; submit unlawful or infringing material; probe vulnerabilities; evade rate limits; misuse calculator outputs; or use the Service to facilitate fraud, discrimination, or unlawful lending or housing practices.</p>
    <h2>5. Your content</h2><p>You retain ownership of content you submit. You grant Clarify a limited, worldwide, non-exclusive license to host, process, reproduce, and display it only as needed to provide, secure, and improve the Service. You represent that you have the rights needed to submit the content.</p>
    <h2>6. Intellectual property</h2><p>The Service, software, design, text, graphics, trademarks, logos, and Clarify content are owned by Clarify or its licensors and protected by intellectual property laws. These Terms provide a limited, revocable, non-transferable right to use the Service; they do not transfer ownership. Third-party names and marks belong to their respective owners.</p>
    <h2>7. Third-party services and links</h2><p>The Service may link to or integrate with lenders, insurers, authentication providers, analytics providers, or other third parties. Clarify does not control and is not responsible for their content, availability, security, privacy practices, products, or decisions. Your use of third-party services is governed by their terms.</p>
    <h2>8. Advertising, sponsorships, and affiliates</h2><p>Clarify may display advertisements, sponsored content, lender or provider matches, and affiliate links. We may receive compensation when you view, click, request information, or complete a transaction. Compensation may affect placement but will not purchase a favorable calculator result. Material relationships will be disclosed as required by law.</p>
    <h2>9. Disclaimers</h2><p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE." CLARIFY DISCLAIMS ALL EXPRESS, IMPLIED, AND STATUTORY WARRANTIES, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, ACCURACY, AND AVAILABILITY. WE DO NOT GUARANTEE SAVINGS, ELIGIBILITY, RATES, TAX RESULTS, INSURANCE PRICES, PROPERTY VALUES, OR THAT THE SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE. VERIFY IMPORTANT INFORMATION WITH A QUALIFIED PROFESSIONAL OR PROVIDER.</p>
    <h2>10. Limitation of liability</h2><p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, CLARIFY AND ITS AFFILIATES, OFFICERS, EMPLOYEES, AND PROVIDERS WILL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, LOST PROFITS, DATA, GOODWILL, OR OPPORTUNITIES ARISING FROM THE SERVICE. OUR TOTAL LIABILITY FOR ALL CLAIMS WILL NOT EXCEED THE GREATER OF US$100 OR THE AMOUNT YOU PAID CLARIFY IN THE 12 MONTHS BEFORE THE EVENT GIVING RISE TO THE CLAIM. Some jurisdictions do not allow certain exclusions, so these limits apply only to the extent permitted.</p>
    <h2>11. Suspension and termination</h2><p>You may stop using the Service at any time. We may suspend or terminate access, remove content, or take protective measures if we reasonably believe you violated these Terms, created risk, failed to pay applicable fees, or used the Service abusively or unlawfully. Provisions that by nature should survive termination will survive.</p>
    <h2>12. Governing law and disputes</h2><p>Unless consumer protection law requires otherwise, these Terms are governed by the laws of the State of Delaware, United States, without regard to conflict-of-law principles, and disputes will be brought in courts with jurisdiction in Delaware. Mandatory rights available where you live are not limited by this section.</p>
    <h2>13. Changes</h2><p>We may update these Terms. We will post the updated version and effective date and provide additional notice for material changes when required. Continued use after changes become effective constitutes acceptance where permitted by law.</p>
    <h2>14. Contact</h2><p>Questions about these Terms may be sent to <a href="mailto:legal@useclarifyhome.us">legal@useclarifyhome.us</a>.</p>
  </LegalPage>;
}
