import type { Metadata } from "next";
import { LegalMeta, LegalPage } from "@/components/legal/legal-page";

export const metadata: Metadata = { title: "Privacy Policy", description: "How Clarify collects, uses, shares, and protects personal information." };

export default function PrivacyPage() {
  return <LegalPage title="Privacy Policy" description="This policy explains how Clarify handles personal information when you use our homeowner intelligence tools and services."><LegalMeta />
    <h2>1. Who we are</h2><p>Clarify ("Clarify," "we," "us," or "our") provides mortgage and homeowner financial education tools. This policy applies to our websites, applications, calculators, accounts, support channels, and related services (the "Service"). Clarify is intended for a global audience, subject to local availability and law.</p>
    <h2>2. Information we collect</h2><p>Depending on how you use the Service, we may collect:</p><ul><li><strong>Account and contact information:</strong> name, email address, authentication identifiers, and account preferences.</li><li><strong>User-provided content:</strong> calculator inputs, saved scenarios, feedback, support messages, and other content you submit. Avoid entering sensitive identifiers into free-text fields.</li><li><strong>Usage and device data:</strong> pages viewed, interactions, referring URLs, approximate location derived from IP address, IP address, browser type, operating system, device identifiers, timestamps, and diagnostic logs.</li><li><strong>Cookies and similar technologies:</strong> essential storage for security and sessions and, only where permitted by your choices and applicable law, analytics or advertising technologies.</li></ul><p>Our calculators can generally be used without providing a name or email. Calculator inputs may be processed in your browser unless a feature clearly indicates that information will be saved or submitted.</p>
    <h2>3. How we use information</h2><ul><li>Provide, operate, personalize, and maintain the Service.</li><li>Authenticate users and manage accounts and sessions.</li><li>Protect security, prevent fraud and abuse, and enforce our Terms.</li><li>Measure performance and understand usage when analytics consent is provided where required.</li><li>Debug, research, and improve products, calculators, and accessibility.</li><li>Respond to questions and provide customer support.</li><li>Send service communications and, with any consent required by law, marketing communications. You may unsubscribe from marketing at any time.</li><li>Comply with law, legal process, and protect rights and safety.</li></ul>
    <h2>4. How we disclose information</h2><p>We may disclose information to service providers acting on our instructions, including <strong>Cloudflare</strong> for hosting, content delivery, security, and network services; <strong>Clerk</strong> for authentication; and <strong>Supabase</strong> for database and storage services. If enabled with the required consent, we may use <strong>Google Analytics</strong> and <strong>Microsoft Clarity</strong> for analytics, and <strong>Google AdSense</strong> or future advertising partners for advertising and measurement.</p><p>We may also disclose information to professional advisers, authorities when legally required, parties involved in a merger, financing, acquisition, or sale of assets, and others at your direction. We do not authorize service providers to use personal information for their own purposes beyond providing contracted services, except as permitted by law.</p>
    <h2>5. Advertising, sale, and sharing</h2><p>Clarify does not currently load advertising technology before you opt in. Some advertising or cross-context behavioral advertising activities may be considered a "sale" or "sharing" under California law even when money is not exchanged. Where applicable, you may opt out through Cookie Settings or by contacting us. We honor recognized Global Privacy Control signals for the browser sending the signal.</p>
    <h2>6. International data transfers</h2><p>Clarify is globally accessible. We and our providers may process information in the United States and other countries whose privacy laws may differ from yours. Where required, we use appropriate safeguards for international transfers, such as standard contractual clauses, provider transfer mechanisms, or another lawful basis.</p>
    <h2>7. Data retention</h2><p>We retain personal information only as long as reasonably necessary for the purposes described here, including providing the Service, maintaining security and records, resolving disputes, and meeting legal obligations. Account information is generally retained while an account is active and for a limited period afterward. Security logs and backups may persist for a limited period under provider retention schedules. Consent records remain stored in your browser until deleted or replaced. When you request account deletion, we delete or de-identify eligible information, subject to legal, security, fraud-prevention, backup, and dispute-resolution exceptions.</p>
    <h2>8. Your privacy rights</h2><p>Rights vary by location. Subject to applicable exceptions and verification, you may request access, correction, deletion, restriction of processing, portability, or objection to processing. You may withdraw consent at any time without affecting prior lawful processing and may complain to your local data protection authority.</p><p>California residents may have rights to know the categories, sources, purposes, and recipients of personal information; access specific information; delete or correct information; and opt out of sale, sharing, or targeted advertising. We will not discriminate against you for exercising a privacy right. Authorized agents may submit requests where permitted by law.</p><p>Submit a request to <a href="mailto:privacy@useclarifyhome.us">privacy@useclarifyhome.us</a>. We may need to verify your identity and authority before completing a request. We will respond within the period required by applicable law.</p>
    <h2>9. Legal bases for EEA, UK, and Swiss users</h2><p>Where applicable, we process information based on performance of a contract, legitimate interests such as security and product operation, compliance with legal obligations, or your consent. You can withdraw consent through Cookie Settings.</p>
    <h2>10. Security</h2><p>We use administrative, technical, and organizational safeguards appropriate to the nature of the information, including encryption in transit, provider encryption at rest where supported, access controls, least-privilege practices, monitoring, and secure development practices. No system is completely secure, and we cannot guarantee absolute security.</p>
    <h2>11. Children</h2><p>The Service is not directed to children under 13, and we do not knowingly collect personal information from children under 13. Users must be at least 18, or the age of legal majority where they live, to create an account or use features involving financial decisions. If you believe a child provided information, contact us so we can investigate and delete it as appropriate.</p>
    <h2>12. Changes and contact</h2><p>We may update this policy. We will post the revised version, update the date above, and provide additional notice when required. Privacy questions and requests may be sent to <a href="mailto:privacy@useclarifyhome.us">privacy@useclarifyhome.us</a>.</p>
  </LegalPage>;
}
